### Assignment 1 Solution

## Objective: - Predict Next Sequence To start with deep learning, the very basic project that you can build is to predict the next digit in a sequence.

Dataset:
Create a sequence like a list of odd numbers and then build a model and train it to predict the next digit in the sequence.

Task: - A simple neural network with 2 layers would be sufficient to build the model.

In [8]:
# Generate a list of the first n odd numbers
n = 100  # Length of the sequence
odd_numbers = [i for i in range(1, 2*n, 2)]
odd_numbers


[1,
 3,
 5,
 7,
 9,
 11,
 13,
 15,
 17,
 19,
 21,
 23,
 25,
 27,
 29,
 31,
 33,
 35,
 37,
 39,
 41,
 43,
 45,
 47,
 49,
 51,
 53,
 55,
 57,
 59,
 61,
 63,
 65,
 67,
 69,
 71,
 73,
 75,
 77,
 79,
 81,
 83,
 85,
 87,
 89,
 91,
 93,
 95,
 97,
 99,
 101,
 103,
 105,
 107,
 109,
 111,
 113,
 115,
 117,
 119,
 121,
 123,
 125,
 127,
 129,
 131,
 133,
 135,
 137,
 139,
 141,
 143,
 145,
 147,
 149,
 151,
 153,
 155,
 157,
 159,
 161,
 163,
 165,
 167,
 169,
 171,
 173,
 175,
 177,
 179,
 181,
 183,
 185,
 187,
 189,
 191,
 193,
 195,
 197,
 199]

In [9]:
import numpy as np

# Create input-output pairs
X = np.array(odd_numbers[:-1]).reshape(-1, 1)  # All odd numbers except the last one
y = np.array(odd_numbers[1:])  # All odd numbers except the first one

X[:5], y[:5]  # Show the first 5 pairs


(array([[1],
        [3],
        [5],
        [7],
        [9]]),
 array([ 3,  5,  7,  9, 11]))

In [10]:
from keras.models import Sequential
from keras.layers import Dense

# Define the model
model = Sequential()
model.add(Dense(10, input_dim=1, activation='relu'))
model.add(Dense(1))

# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error')


In [11]:
# Train the model
model.fit(X, y, epochs=100, verbose=0)


In [12]:
# Predict the next number in the sequence
last_number = np.array([odd_numbers[-1]]).reshape(-1, 1)
next_number_prediction = model.predict(last_number)
next_number_prediction


1/1 [==============================] - 0s 42ms/step


array([[201.58409]], dtype=float32)